language: python
sudo: false
dist: xenial
services:
  - docker
cache: pip
before_cache:
  - chown -R travis:travis $HOME/.cache/pip
stages:
  - style
  - test
matrix:
  include:
    - stage: style
      python: 3.7
      install:
        - pip install -r requirements-dev.txt
      script:
        - make check
    - stage: test
      python: 3.7
      install:
        - travis_retry make bblfsh-start
        - pip install --upgrade pip cython codecov
        - pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp37-cp37m-linux_x86_64.whl
        - pip install .
      script:
        - coverage run --concurrency=multiprocessing -m unittest discover
        - coverage combine
      after_success:
        - codecov
  fast_finish: true
notifications:
  email: false
